{% set name = "marvin" %}
{% set version = "2.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f96628c5e7292ef02cf4bc1f4e6692df23cd1622e4f8c7cfcb2190bda38619d6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [win]

requirements:
  host:
    - python
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  # currently equviland to marvin["all"]. could create sub packages in the future
  run:
    - python
    - cachetools >=5
    - fastapi
    - httpx >=0.24.1
    - jinja2 >=3.1.2
    - jsonpatch >=1.33
    - openai >=1.21.0
    - opencv-python >= 4.5
    - prompt-toolkit >=3.0.33
    - PyAudio >=0.2.11
    - pydantic >=2.4.2
    - pydantic-settings
    - pydub >=0.25
    - python-tzdata >=2023.3
    - rich >=12
    - simpleaudio >=1.0
    - SpeechRecognition >=3.10
    - tiktoken >=0.4.0
    - typer >=0.9.0
    - typing_extensions >=4.0.0
    - uvicorn >=0.22.0
    - partialjson >=0.0.5

test:
  requires:
    - python
  imports:
    - marvin
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.askmarvin.ai/
  summary: A lightweight AI engineering toolkit for building natural language interfaces that are reliable, scalable, and easy to trust
  description: A lightweight AI engineering toolkit for building natural language interfaces that are reliable, scalable, and easy to trust
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://www.askmarvin.ai/
  dev_url: https://github.com/PrefectHQ/marvin

extra:
  recipe-maintainers:
    - raybellwaves
  
